In [1]:
import pandas as pd

In [ ]:
msa_df = pd.read_excel (r'E:\MS_DAEN\DAEN690\Datasets\all_data_M_2021.xlsx')

In [ ]:
msa_df

In [4]:
areadef_df = pd.read_excel (r'area_definitions_m2021.xlsx')

In [10]:
areadef_df.columns

Index(['FIPS code', 'State', 'State abbreviation', 'May 2021 MSA code ',
       'May 2021 MSA name', 'County code', 'Township code',
       'County name (or Township name for the New England states)'],
      dtype='object')

In [13]:
areadef_df = areadef_df.astype (str)
areadef_df['May 2021 MSA code '] = areadef_df['May 2021 MSA code '].str.strip()

In [15]:
msa_df = msa_df.astype (str)

In [16]:
#combinedf=pd.merge(msa_df, areadef_df, on=('AREA','May 2021 MSA code'))
combinedf = pd.merge(msa_df, areadef_df, how='left', left_on=['PRIM_STATE','AREA'], right_on=['State abbreviation','May 2021 MSA code '])

In [18]:
combinedf.columns

Index(['AREA', 'AREA_TITLE', 'AREA_TYPE', 'PRIM_STATE', 'NAICS', 'NAICS_TITLE',
       'I_GROUP', 'OWN_CODE', 'OCC_CODE', 'OCC_TITLE', 'O_GROUP', 'TOT_EMP',
       'EMP_PRSE', 'JOBS_1000', 'LOC_QUOTIENT', 'PCT_TOTAL', 'PCT_RPT',
       'H_MEAN', 'A_MEAN', 'MEAN_PRSE', 'H_PCT10', 'H_PCT25', 'H_MEDIAN',
       'H_PCT75', 'H_PCT90', 'A_PCT10', 'A_PCT25', 'A_MEDIAN', 'A_PCT75',
       'A_PCT90', 'ANNUAL', 'HOURLY', 'FIPS code', 'State',
       'State abbreviation', 'May 2021 MSA code ', 'May 2021 MSA name',
       'County code', 'Township code',
       'County name (or Township name for the New England states)'],
      dtype='object')

In [26]:
combinedf_new = combinedf[['AREA', 'AREA_TITLE', 'AREA_TYPE','PRIM_STATE','State','State abbreviation', 'May 2021 MSA code ', 'May 2021 MSA name', 'County code', 'Township code','County name (or Township name for the New England states)']]

In [27]:
combinedf[combinedf.isna().any(axis=1)]

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,ANNUAL,HOURLY,FIPS code,State,State abbreviation,May 2021 MSA code,May 2021 MSA name,County code,Township code,County name (or Township name for the New England states)
816570,6600001,Guam,6,GU,0,Cross-industry,cross-industry,1235,00-0000,All Occupations,...,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
816571,7800001,Virgin Islands,6,VI,0,Cross-industry,cross-industry,1235,00-0000,All Occupations,...,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
819587,6600001,Guam,6,GU,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
819600,7800001,Virgin Islands,6,VI,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
822421,6600001,Guam,6,GU,0,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1914915,7800001,Virgin Islands,6,VI,0,Cross-industry,cross-industry,1235,53-7064,"Packers and Packagers, Hand",...,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1917931,6600001,Guam,6,GU,0,Cross-industry,cross-industry,1235,53-7065,Stockers and Order Fillers,...,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1917944,7800001,Virgin Islands,6,VI,0,Cross-industry,cross-industry,1235,53-7065,Stockers and Order Fillers,...,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1921926,6600001,Guam,6,GU,0,Cross-industry,cross-industry,1235,53-7081,Refuse and Recyclable Material Collectors,...,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1922789,6600001,Guam,6,GU,0,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",...,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
combinedf_new.to_csv(r'msa_county.csv')